// Code generated by protoc-gen-go. DO NOT EDIT.
// source: aql.proto

/*
Package aql is a generated protocol buffer package.

It is generated from these files:
	aql.proto

It has these top-level messages:
	GraphQuery
	GraphQuerySet
	GraphStatement
	HasStatement
	HasValueStatement
	SelectStatement
	FoldStatement
	VertexMatch
	GenMatch
	EdgeGen
	Vertex
	Edge
	Bundle
	QueryResult
	ResultRow
	EditResult
	GraphElement
	Graph
	ElementID
	Timestamp
	Empty
*/
package aql

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/struct"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Condition int32

const (
	Condition_UNKNOWN Condition = 0
	Condition_EQ      Condition = 1
	Condition_NEQ     Condition = 2
	Condition_GT      Condition = 3
	Condition_GTE     Condition = 4
	Condition_LT      Condition = 5
	Condition_LTE     Condition = 6
	Condition_BETWEEN Condition = 7
	Condition_INSIDE  Condition = 8
	Condition_OUTSIDE Condition = 9
	Condition_WITHIN  Condition = 10
	Condition_WITHOUT Condition = 11
)

var Condition_name = map[int32]string{
	0:  "UNKNOWN",
	1:  "EQ",
	2:  "NEQ",
	3:  "GT",
	4:  "GTE",
	5:  "LT",
	6:  "LTE",
	7:  "BETWEEN",
	8:  "INSIDE",
	9:  "OUTSIDE",
	10: "WITHIN",
	11: "WITHOUT",
}
var Condition_value = map[string]int32{
	"UNKNOWN": 0,
	"EQ":      1,
	"NEQ":     2,
	"GT":      3,
	"GTE":     4,
	"LT":      5,
	"LTE":     6,
	"BETWEEN": 7,
	"INSIDE":  8,
	"OUTSIDE": 9,
	"WITHIN":  10,
	"WITHOUT": 11,
}

func (x Condition) String() string {
	return proto.EnumName(Condition_name, int32(x))
}
func (Condition) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type GraphQuery struct {
	Graph string            `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Query []*GraphStatement `protobuf:"bytes,2,rep,name=query" json:"query,omitempty"`
}

func (m *GraphQuery) Reset()                    { *m = GraphQuery{} }
func (m *GraphQuery) String() string            { return proto.CompactTextString(m) }
func (*GraphQuery) ProtoMessage()               {}
func (*GraphQuery) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GraphQuery) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *GraphQuery) GetQuery() []*GraphStatement {
	if m != nil {
		return m.Query
	}
	return nil
}

type GraphQuerySet struct {
	Queries []*GraphQuery `protobuf:"bytes,1,rep,name=queries" json:"queries,omitempty"`
}

func (m *GraphQuerySet) Reset()                    { *m = GraphQuerySet{} }
func (m *GraphQuerySet) String() string            { return proto.CompactTextString(m) }
func (*GraphQuerySet) ProtoMessage()               {}
func (*GraphQuerySet) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GraphQuerySet) GetQueries() []*GraphQuery {
	if m != nil {
		return m.Queries
	}
	return nil
}

type GraphStatement struct {
	// Types that are valid to be assigned to Statement:
	//	*GraphStatement_V
	//	*GraphStatement_E
	//	*GraphStatement_Has
	//	*GraphStatement_HasLabel
	//	*GraphStatement_HasId
	//	*GraphStatement_HasValue
	//	*GraphStatement_In
	//	*GraphStatement_Out
	//	*GraphStatement_InEdge
	//	*GraphStatement_OutEdge
	//	*GraphStatement_Both
	//	*GraphStatement_BothEdge
	//	*GraphStatement_OutBundle
	//	*GraphStatement_As
	//	*GraphStatement_Select
	//	*GraphStatement_Values
	//	*GraphStatement_Limit
	//	*GraphStatement_Count
	//	*GraphStatement_GroupCount
	//	*GraphStatement_Match
	//	*GraphStatement_Import
	//	*GraphStatement_Map
	//	*GraphStatement_Fold
	//	*GraphStatement_VertexFold
	//	*GraphStatement_Filter
	//	*GraphStatement_FilterValues
	//	*GraphStatement_VertexFromValues
	Statement isGraphStatement_Statement `protobuf_oneof:"statement"`
}

func (m *GraphStatement) Reset()                    { *m = GraphStatement{} }
func (m *GraphStatement) String() string            { return proto.CompactTextString(m) }
func (*GraphStatement) ProtoMessage()               {}
func (*GraphStatement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type isGraphStatement_Statement interface {
	isGraphStatement_Statement()
}

type GraphStatement_V struct {
	V *google_protobuf1.ListValue `protobuf:"bytes,1,opt,name=V,oneof"`
}
type GraphStatement_E struct {
	E string `protobuf:"bytes,2,opt,name=E,oneof"`
}
type GraphStatement_Has struct {
	Has *HasStatement `protobuf:"bytes,5,opt,name=has,oneof"`
}
type GraphStatement_HasLabel struct {
	HasLabel *google_protobuf1.ListValue `protobuf:"bytes,6,opt,name=hasLabel,oneof"`
}
type GraphStatement_HasId struct {
	HasId *google_protobuf1.ListValue `protobuf:"bytes,7,opt,name=hasId,oneof"`
}
type GraphStatement_HasValue struct {
	HasValue *HasValueStatement `protobuf:"bytes,8,opt,name=hasValue,oneof"`
}
type GraphStatement_In struct {
	In *google_protobuf1.ListValue `protobuf:"bytes,10,opt,name=in,oneof"`
}
type GraphStatement_Out struct {
	Out *google_protobuf1.ListValue `protobuf:"bytes,11,opt,name=out,oneof"`
}
type GraphStatement_InEdge struct {
	InEdge *google_protobuf1.ListValue `protobuf:"bytes,12,opt,name=inEdge,oneof"`
}
type GraphStatement_OutEdge struct {
	OutEdge *google_protobuf1.ListValue `protobuf:"bytes,13,opt,name=outEdge,oneof"`
}
type GraphStatement_Both struct {
	Both *google_protobuf1.ListValue `protobuf:"bytes,14,opt,name=both,oneof"`
}
type GraphStatement_BothEdge struct {
	BothEdge *google_protobuf1.ListValue `protobuf:"bytes,15,opt,name=bothEdge,oneof"`
}
type GraphStatement_OutBundle struct {
	OutBundle *google_protobuf1.ListValue `protobuf:"bytes,16,opt,name=outBundle,oneof"`
}
type GraphStatement_As struct {
	As string `protobuf:"bytes,20,opt,name=as,oneof"`
}
type GraphStatement_Select struct {
	Select *SelectStatement `protobuf:"bytes,21,opt,name=select,oneof"`
}
type GraphStatement_Values struct {
	Values *SelectStatement `protobuf:"bytes,22,opt,name=values,oneof"`
}
type GraphStatement_Limit struct {
	Limit int64 `protobuf:"varint,25,opt,name=limit,oneof"`
}
type GraphStatement_Count struct {
	Count string `protobuf:"bytes,26,opt,name=count,oneof"`
}
type GraphStatement_GroupCount struct {
	GroupCount string `protobuf:"bytes,30,opt,name=groupCount,oneof"`
}
type GraphStatement_Match struct {
	Match *GraphQuerySet `protobuf:"bytes,40,opt,name=match,oneof"`
}
type GraphStatement_Import struct {
	Import string `protobuf:"bytes,50,opt,name=import,oneof"`
}
type GraphStatement_Map struct {
	Map string `protobuf:"bytes,51,opt,name=map,oneof"`
}
type GraphStatement_Fold struct {
	Fold *FoldStatement `protobuf:"bytes,52,opt,name=fold,oneof"`
}
type GraphStatement_VertexFold struct {
	VertexFold *FoldStatement `protobuf:"bytes,53,opt,name=vertexFold,oneof"`
}
type GraphStatement_Filter struct {
	Filter string `protobuf:"bytes,54,opt,name=filter,oneof"`
}
type GraphStatement_FilterValues struct {
	FilterValues string `protobuf:"bytes,55,opt,name=filterValues,oneof"`
}
type GraphStatement_VertexFromValues struct {
	VertexFromValues string `protobuf:"bytes,56,opt,name=vertexFromValues,oneof"`
}

func (*GraphStatement_V) isGraphStatement_Statement()                {}
func (*GraphStatement_E) isGraphStatement_Statement()                {}
func (*GraphStatement_Has) isGraphStatement_Statement()              {}
func (*GraphStatement_HasLabel) isGraphStatement_Statement()         {}
func (*GraphStatement_HasId) isGraphStatement_Statement()            {}
func (*GraphStatement_HasValue) isGraphStatement_Statement()         {}
func (*GraphStatement_In) isGraphStatement_Statement()               {}
func (*GraphStatement_Out) isGraphStatement_Statement()              {}
func (*GraphStatement_InEdge) isGraphStatement_Statement()           {}
func (*GraphStatement_OutEdge) isGraphStatement_Statement()          {}
func (*GraphStatement_Both) isGraphStatement_Statement()             {}
func (*GraphStatement_BothEdge) isGraphStatement_Statement()         {}
func (*GraphStatement_OutBundle) isGraphStatement_Statement()        {}
func (*GraphStatement_As) isGraphStatement_Statement()               {}
func (*GraphStatement_Select) isGraphStatement_Statement()           {}
func (*GraphStatement_Values) isGraphStatement_Statement()           {}
func (*GraphStatement_Limit) isGraphStatement_Statement()            {}
func (*GraphStatement_Count) isGraphStatement_Statement()            {}
func (*GraphStatement_GroupCount) isGraphStatement_Statement()       {}
func (*GraphStatement_Match) isGraphStatement_Statement()            {}
func (*GraphStatement_Import) isGraphStatement_Statement()           {}
func (*GraphStatement_Map) isGraphStatement_Statement()              {}
func (*GraphStatement_Fold) isGraphStatement_Statement()             {}
func (*GraphStatement_VertexFold) isGraphStatement_Statement()       {}
func (*GraphStatement_Filter) isGraphStatement_Statement()           {}
func (*GraphStatement_FilterValues) isGraphStatement_Statement()     {}
func (*GraphStatement_VertexFromValues) isGraphStatement_Statement() {}

func (m *GraphStatement) GetStatement() isGraphStatement_Statement {
	if m != nil {
		return m.Statement
	}
	return nil
}

func (m *GraphStatement) GetV() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_V); ok {
		return x.V
	}
	return nil
}

func (m *GraphStatement) GetE() string {
	if x, ok := m.GetStatement().(*GraphStatement_E); ok {
		return x.E
	}
	return ""
}

func (m *GraphStatement) GetHas() *HasStatement {
	if x, ok := m.GetStatement().(*GraphStatement_Has); ok {
		return x.Has
	}
	return nil
}

func (m *GraphStatement) GetHasLabel() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_HasLabel); ok {
		return x.HasLabel
	}
	return nil
}

func (m *GraphStatement) GetHasId() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_HasId); ok {
		return x.HasId
	}
	return nil
}

func (m *GraphStatement) GetHasValue() *HasValueStatement {
	if x, ok := m.GetStatement().(*GraphStatement_HasValue); ok {
		return x.HasValue
	}
	return nil
}

func (m *GraphStatement) GetIn() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_In); ok {
		return x.In
	}
	return nil
}

func (m *GraphStatement) GetOut() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_Out); ok {
		return x.Out
	}
	return nil
}

func (m *GraphStatement) GetInEdge() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_InEdge); ok {
		return x.InEdge
	}
	return nil
}

func (m *GraphStatement) GetOutEdge() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_OutEdge); ok {
		return x.OutEdge
	}
	return nil
}

func (m *GraphStatement) GetBoth() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_Both); ok {
		return x.Both
	}
	return nil
}

func (m *GraphStatement) GetBothEdge() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_BothEdge); ok {
		return x.BothEdge
	}
	return nil
}

func (m *GraphStatement) GetOutBundle() *google_protobuf1.ListValue {
	if x, ok := m.GetStatement().(*GraphStatement_OutBundle); ok {
		return x.OutBundle
	}
	return nil
}

func (m *GraphStatement) GetAs() string {
	if x, ok := m.GetStatement().(*GraphStatement_As); ok {
		return x.As
	}
	return ""
}

func (m *GraphStatement) GetSelect() *SelectStatement {
	if x, ok := m.GetStatement().(*GraphStatement_Select); ok {
		return x.Select
	}
	return nil
}

func (m *GraphStatement) GetValues() *SelectStatement {
	if x, ok := m.GetStatement().(*GraphStatement_Values); ok {
		return x.Values
	}
	return nil
}

func (m *GraphStatement) GetLimit() int64 {
	if x, ok := m.GetStatement().(*GraphStatement_Limit); ok {
		return x.Limit
	}
	return 0
}

func (m *GraphStatement) GetCount() string {
	if x, ok := m.GetStatement().(*GraphStatement_Count); ok {
		return x.Count
	}
	return ""
}

func (m *GraphStatement) GetGroupCount() string {
	if x, ok := m.GetStatement().(*GraphStatement_GroupCount); ok {
		return x.GroupCount
	}
	return ""
}

func (m *GraphStatement) GetMatch() *GraphQuerySet {
	if x, ok := m.GetStatement().(*GraphStatement_Match); ok {
		return x.Match
	}
	return nil
}

func (m *GraphStatement) GetImport() string {
	if x, ok := m.GetStatement().(*GraphStatement_Import); ok {
		return x.Import
	}
	return ""
}

func (m *GraphStatement) GetMap() string {
	if x, ok := m.GetStatement().(*GraphStatement_Map); ok {
		return x.Map
	}
	return ""
}

func (m *GraphStatement) GetFold() *FoldStatement {
	if x, ok := m.GetStatement().(*GraphStatement_Fold); ok {
		return x.Fold
	}
	return nil
}

func (m *GraphStatement) GetVertexFold() *FoldStatement {
	if x, ok := m.GetStatement().(*GraphStatement_VertexFold); ok {
		return x.VertexFold
	}
	return nil
}

func (m *GraphStatement) GetFilter() string {
	if x, ok := m.GetStatement().(*GraphStatement_Filter); ok {
		return x.Filter
	}
	return ""
}

func (m *GraphStatement) GetFilterValues() string {
	if x, ok := m.GetStatement().(*GraphStatement_FilterValues); ok {
		return x.FilterValues
	}
	return ""
}

func (m *GraphStatement) GetVertexFromValues() string {
	if x, ok := m.GetStatement().(*GraphStatement_VertexFromValues); ok {
		return x.VertexFromValues
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*GraphStatement) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _GraphStatement_OneofMarshaler, _GraphStatement_OneofUnmarshaler, _GraphStatement_OneofSizer, []interface{}{
		(*GraphStatement_V)(nil),
		(*GraphStatement_E)(nil),
		(*GraphStatement_Has)(nil),
		(*GraphStatement_HasLabel)(nil),
		(*GraphStatement_HasId)(nil),
		(*GraphStatement_HasValue)(nil),
		(*GraphStatement_In)(nil),
		(*GraphStatement_Out)(nil),
		(*GraphStatement_InEdge)(nil),
		(*GraphStatement_OutEdge)(nil),
		(*GraphStatement_Both)(nil),
		(*GraphStatement_BothEdge)(nil),
		(*GraphStatement_OutBundle)(nil),
		(*GraphStatement_As)(nil),
		(*GraphStatement_Select)(nil),
		(*GraphStatement_Values)(nil),
		(*GraphStatement_Limit)(nil),
		(*GraphStatement_Count)(nil),
		(*GraphStatement_GroupCount)(nil),
		(*GraphStatement_Match)(nil),
		(*GraphStatement_Import)(nil),
		(*GraphStatement_Map)(nil),
		(*GraphStatement_Fold)(nil),
		(*GraphStatement_VertexFold)(nil),
		(*GraphStatement_Filter)(nil),
		(*GraphStatement_FilterValues)(nil),
		(*GraphStatement_VertexFromValues)(nil),
	}
}

func _GraphStatement_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*GraphStatement)
	// statement
	switch x := m.Statement.(type) {
	case *GraphStatement_V:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.V); err != nil {
			return err
		}
	case *GraphStatement_E:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.E)
	case *GraphStatement_Has:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Has); err != nil {
			return err
		}
	case *GraphStatement_HasLabel:
		b.EncodeVarint(6<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HasLabel); err != nil {
			return err
		}
	case *GraphStatement_HasId:
		b.EncodeVarint(7<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HasId); err != nil {
			return err
		}
	case *GraphStatement_HasValue:
		b.EncodeVarint(8<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.HasValue); err != nil {
			return err
		}
	case *GraphStatement_In:
		b.EncodeVarint(10<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.In); err != nil {
			return err
		}
	case *GraphStatement_Out:
		b.EncodeVarint(11<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Out); err != nil {
			return err
		}
	case *GraphStatement_InEdge:
		b.EncodeVarint(12<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.InEdge); err != nil {
			return err
		}
	case *GraphStatement_OutEdge:
		b.EncodeVarint(13<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OutEdge); err != nil {
			return err
		}
	case *GraphStatement_Both:
		b.EncodeVarint(14<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Both); err != nil {
			return err
		}
	case *GraphStatement_BothEdge:
		b.EncodeVarint(15<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.BothEdge); err != nil {
			return err
		}
	case *GraphStatement_OutBundle:
		b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.OutBundle); err != nil {
			return err
		}
	case *GraphStatement_As:
		b.EncodeVarint(20<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.As)
	case *GraphStatement_Select:
		b.EncodeVarint(21<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Select); err != nil {
			return err
		}
	case *GraphStatement_Values:
		b.EncodeVarint(22<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Values); err != nil {
			return err
		}
	case *GraphStatement_Limit:
		b.EncodeVarint(25<<3 | proto.WireVarint)
		b.EncodeVarint(uint64(x.Limit))
	case *GraphStatement_Count:
		b.EncodeVarint(26<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Count)
	case *GraphStatement_GroupCount:
		b.EncodeVarint(30<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.GroupCount)
	case *GraphStatement_Match:
		b.EncodeVarint(40<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Match); err != nil {
			return err
		}
	case *GraphStatement_Import:
		b.EncodeVarint(50<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Import)
	case *GraphStatement_Map:
		b.EncodeVarint(51<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Map)
	case *GraphStatement_Fold:
		b.EncodeVarint(52<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Fold); err != nil {
			return err
		}
	case *GraphStatement_VertexFold:
		b.EncodeVarint(53<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.VertexFold); err != nil {
			return err
		}
	case *GraphStatement_Filter:
		b.EncodeVarint(54<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Filter)
	case *GraphStatement_FilterValues:
		b.EncodeVarint(55<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.FilterValues)
	case *GraphStatement_VertexFromValues:
		b.EncodeVarint(56<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.VertexFromValues)
	case nil:
	default:
		return fmt.Errorf("GraphStatement.Statement has unexpected type %T", x)
	}
	return nil
}

func _GraphStatement_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*GraphStatement)
	switch tag {
	case 1: // statement.V
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_V{msg}
		return true, err
	case 2: // statement.E
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_E{x}
		return true, err
	case 5: // statement.has
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HasStatement)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Has{msg}
		return true, err
	case 6: // statement.hasLabel
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_HasLabel{msg}
		return true, err
	case 7: // statement.hasId
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_HasId{msg}
		return true, err
	case 8: // statement.hasValue
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(HasValueStatement)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_HasValue{msg}
		return true, err
	case 10: // statement.in
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_In{msg}
		return true, err
	case 11: // statement.out
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Out{msg}
		return true, err
	case 12: // statement.inEdge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_InEdge{msg}
		return true, err
	case 13: // statement.outEdge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_OutEdge{msg}
		return true, err
	case 14: // statement.both
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Both{msg}
		return true, err
	case 15: // statement.bothEdge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_BothEdge{msg}
		return true, err
	case 16: // statement.outBundle
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.ListValue)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_OutBundle{msg}
		return true, err
	case 20: // statement.as
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_As{x}
		return true, err
	case 21: // statement.select
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SelectStatement)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Select{msg}
		return true, err
	case 22: // statement.values
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(SelectStatement)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Values{msg}
		return true, err
	case 25: // statement.limit
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.Statement = &GraphStatement_Limit{int64(x)}
		return true, err
	case 26: // statement.count
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_Count{x}
		return true, err
	case 30: // statement.groupCount
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_GroupCount{x}
		return true, err
	case 40: // statement.match
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GraphQuerySet)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Match{msg}
		return true, err
	case 50: // statement.import
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_Import{x}
		return true, err
	case 51: // statement.map
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_Map{x}
		return true, err
	case 52: // statement.fold
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FoldStatement)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_Fold{msg}
		return true, err
	case 53: // statement.vertexFold
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(FoldStatement)
		err := b.DecodeMessage(msg)
		m.Statement = &GraphStatement_VertexFold{msg}
		return true, err
	case 54: // statement.filter
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_Filter{x}
		return true, err
	case 55: // statement.filterValues
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_FilterValues{x}
		return true, err
	case 56: // statement.vertexFromValues
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Statement = &GraphStatement_VertexFromValues{x}
		return true, err
	default:
		return false, nil
	}
}

func _GraphStatement_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*GraphStatement)
	// statement
	switch x := m.Statement.(type) {
	case *GraphStatement_V:
		s := proto.Size(x.V)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_E:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.E)))
		n += len(x.E)
	case *GraphStatement_Has:
		s := proto.Size(x.Has)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_HasLabel:
		s := proto.Size(x.HasLabel)
		n += proto.SizeVarint(6<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_HasId:
		s := proto.Size(x.HasId)
		n += proto.SizeVarint(7<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_HasValue:
		s := proto.Size(x.HasValue)
		n += proto.SizeVarint(8<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_In:
		s := proto.Size(x.In)
		n += proto.SizeVarint(10<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Out:
		s := proto.Size(x.Out)
		n += proto.SizeVarint(11<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_InEdge:
		s := proto.Size(x.InEdge)
		n += proto.SizeVarint(12<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_OutEdge:
		s := proto.Size(x.OutEdge)
		n += proto.SizeVarint(13<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Both:
		s := proto.Size(x.Both)
		n += proto.SizeVarint(14<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_BothEdge:
		s := proto.Size(x.BothEdge)
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_OutBundle:
		s := proto.Size(x.OutBundle)
		n += proto.SizeVarint(16<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_As:
		n += proto.SizeVarint(20<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.As)))
		n += len(x.As)
	case *GraphStatement_Select:
		s := proto.Size(x.Select)
		n += proto.SizeVarint(21<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Values:
		s := proto.Size(x.Values)
		n += proto.SizeVarint(22<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Limit:
		n += proto.SizeVarint(25<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Limit))
	case *GraphStatement_Count:
		n += proto.SizeVarint(26<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Count)))
		n += len(x.Count)
	case *GraphStatement_GroupCount:
		n += proto.SizeVarint(30<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.GroupCount)))
		n += len(x.GroupCount)
	case *GraphStatement_Match:
		s := proto.Size(x.Match)
		n += proto.SizeVarint(40<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Import:
		n += proto.SizeVarint(50<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Import)))
		n += len(x.Import)
	case *GraphStatement_Map:
		n += proto.SizeVarint(51<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Map)))
		n += len(x.Map)
	case *GraphStatement_Fold:
		s := proto.Size(x.Fold)
		n += proto.SizeVarint(52<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_VertexFold:
		s := proto.Size(x.VertexFold)
		n += proto.SizeVarint(53<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *GraphStatement_Filter:
		n += proto.SizeVarint(54<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Filter)))
		n += len(x.Filter)
	case *GraphStatement_FilterValues:
		n += proto.SizeVarint(55<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.FilterValues)))
		n += len(x.FilterValues)
	case *GraphStatement_VertexFromValues:
		n += proto.SizeVarint(56<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.VertexFromValues)))
		n += len(x.VertexFromValues)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type HasStatement struct {
	Key    string   `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Within []string `protobuf:"bytes,2,rep,name=within" json:"within,omitempty"`
}

func (m *HasStatement) Reset()                    { *m = HasStatement{} }
func (m *HasStatement) String() string            { return proto.CompactTextString(m) }
func (*HasStatement) ProtoMessage()               {}
func (*HasStatement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *HasStatement) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *HasStatement) GetWithin() []string {
	if m != nil {
		return m.Within
	}
	return nil
}

type HasValueStatement struct {
	Key1      string    `protobuf:"bytes,1,opt,name=key1" json:"key1,omitempty"`
	Key2      string    `protobuf:"bytes,2,opt,name=key2" json:"key2,omitempty"`
	Condition Condition `protobuf:"varint,3,opt,name=condition,enum=aql.Condition" json:"condition,omitempty"`
}

func (m *HasValueStatement) Reset()                    { *m = HasValueStatement{} }
func (m *HasValueStatement) String() string            { return proto.CompactTextString(m) }
func (*HasValueStatement) ProtoMessage()               {}
func (*HasValueStatement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *HasValueStatement) GetKey1() string {
	if m != nil {
		return m.Key1
	}
	return ""
}

func (m *HasValueStatement) GetKey2() string {
	if m != nil {
		return m.Key2
	}
	return ""
}

func (m *HasValueStatement) GetCondition() Condition {
	if m != nil {
		return m.Condition
	}
	return Condition_UNKNOWN
}

type SelectStatement struct {
	Labels []string `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty"`
}

func (m *SelectStatement) Reset()                    { *m = SelectStatement{} }
func (m *SelectStatement) String() string            { return proto.CompactTextString(m) }
func (*SelectStatement) ProtoMessage()               {}
func (*SelectStatement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *SelectStatement) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type FoldStatement struct {
	Source string                  `protobuf:"bytes,1,opt,name=source" json:"source,omitempty"`
	Init   *google_protobuf1.Value `protobuf:"bytes,2,opt,name=init" json:"init,omitempty"`
}

func (m *FoldStatement) Reset()                    { *m = FoldStatement{} }
func (m *FoldStatement) String() string            { return proto.CompactTextString(m) }
func (*FoldStatement) ProtoMessage()               {}
func (*FoldStatement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *FoldStatement) GetSource() string {
	if m != nil {
		return m.Source
	}
	return ""
}

func (m *FoldStatement) GetInit() *google_protobuf1.Value {
	if m != nil {
		return m.Init
	}
	return nil
}

type VertexMatch struct {
	Field string    `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Value []string  `protobuf:"bytes,2,rep,name=value" json:"value,omitempty"`
	Op    Condition `protobuf:"varint,3,opt,name=op,enum=aql.Condition" json:"op,omitempty"`
}

func (m *VertexMatch) Reset()                    { *m = VertexMatch{} }
func (m *VertexMatch) String() string            { return proto.CompactTextString(m) }
func (*VertexMatch) ProtoMessage()               {}
func (*VertexMatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *VertexMatch) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *VertexMatch) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *VertexMatch) GetOp() Condition {
	if m != nil {
		return m.Op
	}
	return Condition_UNKNOWN
}

type GenMatch struct {
	Field string         `protobuf:"bytes,1,opt,name=field" json:"field,omitempty"`
	Match []*VertexMatch `protobuf:"bytes,2,rep,name=match" json:"match,omitempty"`
	Data  string         `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
}

func (m *GenMatch) Reset()                    { *m = GenMatch{} }
func (m *GenMatch) String() string            { return proto.CompactTextString(m) }
func (*GenMatch) ProtoMessage()               {}
func (*GenMatch) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GenMatch) GetField() string {
	if m != nil {
		return m.Field
	}
	return ""
}

func (m *GenMatch) GetMatch() []*VertexMatch {
	if m != nil {
		return m.Match
	}
	return nil
}

func (m *GenMatch) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

type EdgeGen struct {
	Gid   string `protobuf:"bytes,1,opt,name=gid" json:"gid,omitempty"`
	Label string `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	// Types that are valid to be assigned to Build:
	//	*EdgeGen_Unzip
	//	*EdgeGen_Range
	//	*EdgeGen_Match
	Build isEdgeGen_Build `protobuf_oneof:"build"`
}

func (m *EdgeGen) Reset()                    { *m = EdgeGen{} }
func (m *EdgeGen) String() string            { return proto.CompactTextString(m) }
func (*EdgeGen) ProtoMessage()               {}
func (*EdgeGen) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type isEdgeGen_Build interface {
	isEdgeGen_Build()
}

type EdgeGen_Unzip struct {
	Unzip *GenMatch `protobuf:"bytes,3,opt,name=unzip,oneof"`
}
type EdgeGen_Range struct {
	Range *GenMatch `protobuf:"bytes,4,opt,name=range,oneof"`
}
type EdgeGen_Match struct {
	Match *GenMatch `protobuf:"bytes,5,opt,name=match,oneof"`
}

func (*EdgeGen_Unzip) isEdgeGen_Build() {}
func (*EdgeGen_Range) isEdgeGen_Build() {}
func (*EdgeGen_Match) isEdgeGen_Build() {}

func (m *EdgeGen) GetBuild() isEdgeGen_Build {
	if m != nil {
		return m.Build
	}
	return nil
}

func (m *EdgeGen) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *EdgeGen) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *EdgeGen) GetUnzip() *GenMatch {
	if x, ok := m.GetBuild().(*EdgeGen_Unzip); ok {
		return x.Unzip
	}
	return nil
}

func (m *EdgeGen) GetRange() *GenMatch {
	if x, ok := m.GetBuild().(*EdgeGen_Range); ok {
		return x.Range
	}
	return nil
}

func (m *EdgeGen) GetMatch() *GenMatch {
	if x, ok := m.GetBuild().(*EdgeGen_Match); ok {
		return x.Match
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*EdgeGen) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _EdgeGen_OneofMarshaler, _EdgeGen_OneofUnmarshaler, _EdgeGen_OneofSizer, []interface{}{
		(*EdgeGen_Unzip)(nil),
		(*EdgeGen_Range)(nil),
		(*EdgeGen_Match)(nil),
	}
}

func _EdgeGen_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*EdgeGen)
	// build
	switch x := m.Build.(type) {
	case *EdgeGen_Unzip:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Unzip); err != nil {
			return err
		}
	case *EdgeGen_Range:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Range); err != nil {
			return err
		}
	case *EdgeGen_Match:
		b.EncodeVarint(5<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Match); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("EdgeGen.Build has unexpected type %T", x)
	}
	return nil
}

func _EdgeGen_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*EdgeGen)
	switch tag {
	case 3: // build.unzip
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GenMatch)
		err := b.DecodeMessage(msg)
		m.Build = &EdgeGen_Unzip{msg}
		return true, err
	case 4: // build.range
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GenMatch)
		err := b.DecodeMessage(msg)
		m.Build = &EdgeGen_Range{msg}
		return true, err
	case 5: // build.match
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(GenMatch)
		err := b.DecodeMessage(msg)
		m.Build = &EdgeGen_Match{msg}
		return true, err
	default:
		return false, nil
	}
}

func _EdgeGen_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*EdgeGen)
	// build
	switch x := m.Build.(type) {
	case *EdgeGen_Unzip:
		s := proto.Size(x.Unzip)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EdgeGen_Range:
		s := proto.Size(x.Range)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *EdgeGen_Match:
		s := proto.Size(x.Match)
		n += proto.SizeVarint(5<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type Vertex struct {
	Gid   string                   `protobuf:"bytes,1,opt,name=gid" json:"gid,omitempty"`
	Label string                   `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	Data  *google_protobuf1.Struct `protobuf:"bytes,3,opt,name=data" json:"data,omitempty"`
	Gen   []*EdgeGen               `protobuf:"bytes,4,rep,name=gen" json:"gen,omitempty"`
}

func (m *Vertex) Reset()                    { *m = Vertex{} }
func (m *Vertex) String() string            { return proto.CompactTextString(m) }
func (*Vertex) ProtoMessage()               {}
func (*Vertex) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Vertex) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *Vertex) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Vertex) GetData() *google_protobuf1.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Vertex) GetGen() []*EdgeGen {
	if m != nil {
		return m.Gen
	}
	return nil
}

type Edge struct {
	Gid   string                   `protobuf:"bytes,1,opt,name=gid" json:"gid,omitempty"`
	Label string                   `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	From  string                   `protobuf:"bytes,3,opt,name=from" json:"from,omitempty"`
	To    string                   `protobuf:"bytes,4,opt,name=to" json:"to,omitempty"`
	Data  *google_protobuf1.Struct `protobuf:"bytes,5,opt,name=data" json:"data,omitempty"`
}

func (m *Edge) Reset()                    { *m = Edge{} }
func (m *Edge) String() string            { return proto.CompactTextString(m) }
func (*Edge) ProtoMessage()               {}
func (*Edge) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *Edge) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *Edge) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Edge) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Edge) GetTo() string {
	if m != nil {
		return m.To
	}
	return ""
}

func (m *Edge) GetData() *google_protobuf1.Struct {
	if m != nil {
		return m.Data
	}
	return nil
}

type Bundle struct {
	Gid    string                              `protobuf:"bytes,1,opt,name=gid" json:"gid,omitempty"`
	Label  string                              `protobuf:"bytes,2,opt,name=label" json:"label,omitempty"`
	From   string                              `protobuf:"bytes,3,opt,name=from" json:"from,omitempty"`
	Bundle map[string]*google_protobuf1.Struct `protobuf:"bytes,4,rep,name=bundle" json:"bundle,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Bundle) Reset()                    { *m = Bundle{} }
func (m *Bundle) String() string            { return proto.CompactTextString(m) }
func (*Bundle) ProtoMessage()               {}
func (*Bundle) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *Bundle) GetGid() string {
	if m != nil {
		return m.Gid
	}
	return ""
}

func (m *Bundle) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Bundle) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *Bundle) GetBundle() map[string]*google_protobuf1.Struct {
	if m != nil {
		return m.Bundle
	}
	return nil
}

type QueryResult struct {
	// Types that are valid to be assigned to Result:
	//	*QueryResult_Vertex
	//	*QueryResult_Edge
	//	*QueryResult_Bundle
	//	*QueryResult_Data
	Result isQueryResult_Result `protobuf_oneof:"result"`
}

func (m *QueryResult) Reset()                    { *m = QueryResult{} }
func (m *QueryResult) String() string            { return proto.CompactTextString(m) }
func (*QueryResult) ProtoMessage()               {}
func (*QueryResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

type isQueryResult_Result interface {
	isQueryResult_Result()
}

type QueryResult_Vertex struct {
	Vertex *Vertex `protobuf:"bytes,1,opt,name=vertex,oneof"`
}
type QueryResult_Edge struct {
	Edge *Edge `protobuf:"bytes,2,opt,name=edge,oneof"`
}
type QueryResult_Bundle struct {
	Bundle *Bundle `protobuf:"bytes,3,opt,name=bundle,oneof"`
}
type QueryResult_Data struct {
	Data *google_protobuf1.Value `protobuf:"bytes,4,opt,name=data,oneof"`
}

func (*QueryResult_Vertex) isQueryResult_Result() {}
func (*QueryResult_Edge) isQueryResult_Result()   {}
func (*QueryResult_Bundle) isQueryResult_Result() {}
func (*QueryResult_Data) isQueryResult_Result()   {}

func (m *QueryResult) GetResult() isQueryResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *QueryResult) GetVertex() *Vertex {
	if x, ok := m.GetResult().(*QueryResult_Vertex); ok {
		return x.Vertex
	}
	return nil
}

func (m *QueryResult) GetEdge() *Edge {
	if x, ok := m.GetResult().(*QueryResult_Edge); ok {
		return x.Edge
	}
	return nil
}

func (m *QueryResult) GetBundle() *Bundle {
	if x, ok := m.GetResult().(*QueryResult_Bundle); ok {
		return x.Bundle
	}
	return nil
}

func (m *QueryResult) GetData() *google_protobuf1.Value {
	if x, ok := m.GetResult().(*QueryResult_Data); ok {
		return x.Data
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*QueryResult) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _QueryResult_OneofMarshaler, _QueryResult_OneofUnmarshaler, _QueryResult_OneofSizer, []interface{}{
		(*QueryResult_Vertex)(nil),
		(*QueryResult_Edge)(nil),
		(*QueryResult_Bundle)(nil),
		(*QueryResult_Data)(nil),
	}
}

func _QueryResult_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*QueryResult)
	// result
	switch x := m.Result.(type) {
	case *QueryResult_Vertex:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Vertex); err != nil {
			return err
		}
	case *QueryResult_Edge:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Edge); err != nil {
			return err
		}
	case *QueryResult_Bundle:
		b.EncodeVarint(3<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Bundle); err != nil {
			return err
		}
	case *QueryResult_Data:
		b.EncodeVarint(4<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.Data); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("QueryResult.Result has unexpected type %T", x)
	}
	return nil
}

func _QueryResult_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*QueryResult)
	switch tag {
	case 1: // result.vertex
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Vertex)
		err := b.DecodeMessage(msg)
		m.Result = &QueryResult_Vertex{msg}
		return true, err
	case 2: // result.edge
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Edge)
		err := b.DecodeMessage(msg)
		m.Result = &QueryResult_Edge{msg}
		return true, err
	case 3: // result.bundle
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Bundle)
		err := b.DecodeMessage(msg)
		m.Result = &QueryResult_Bundle{msg}
		return true, err
	case 4: // result.data
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(google_protobuf1.Value)
		err := b.DecodeMessage(msg)
		m.Result = &QueryResult_Data{msg}
		return true, err
	default:
		return false, nil
	}
}

func _QueryResult_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*QueryResult)
	// result
	switch x := m.Result.(type) {
	case *QueryResult_Vertex:
		s := proto.Size(x.Vertex)
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueryResult_Edge:
		s := proto.Size(x.Edge)
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueryResult_Bundle:
		s := proto.Size(x.Bundle)
		n += proto.SizeVarint(3<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case *QueryResult_Data:
		s := proto.Size(x.Data)
		n += proto.SizeVarint(4<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type ResultRow struct {
	Value *QueryResult   `protobuf:"bytes,1,opt,name=value" json:"value,omitempty"`
	Row   []*QueryResult `protobuf:"bytes,2,rep,name=row" json:"row,omitempty"`
}

func (m *ResultRow) Reset()                    { *m = ResultRow{} }
func (m *ResultRow) String() string            { return proto.CompactTextString(m) }
func (*ResultRow) ProtoMessage()               {}
func (*ResultRow) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ResultRow) GetValue() *QueryResult {
	if m != nil {
		return m.Value
	}
	return nil
}

func (m *ResultRow) GetRow() []*QueryResult {
	if m != nil {
		return m.Row
	}
	return nil
}

type EditResult struct {
	// Types that are valid to be assigned to Result:
	//	*EditResult_Error
	//	*EditResult_Id
	Result isEditResult_Result `protobuf_oneof:"result"`
}

func (m *EditResult) Reset()                    { *m = EditResult{} }
func (m *EditResult) String() string            { return proto.CompactTextString(m) }
func (*EditResult) ProtoMessage()               {}
func (*EditResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type isEditResult_Result interface {
	isEditResult_Result()
}

type EditResult_Error struct {
	Error string `protobuf:"bytes,1,opt,name=error,oneof"`
}
type EditResult_Id struct {
	Id string `protobuf:"bytes,2,opt,name=id,oneof"`
}

func (*EditResult_Error) isEditResult_Result() {}
func (*EditResult_Id) isEditResult_Result()    {}

func (m *EditResult) GetResult() isEditResult_Result {
	if m != nil {
		return m.Result
	}
	return nil
}

func (m *EditResult) GetError() string {
	if x, ok := m.GetResult().(*EditResult_Error); ok {
		return x.Error
	}
	return ""
}

func (m *EditResult) GetId() string {
	if x, ok := m.GetResult().(*EditResult_Id); ok {
		return x.Id
	}
	return ""
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*EditResult) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _EditResult_OneofMarshaler, _EditResult_OneofUnmarshaler, _EditResult_OneofSizer, []interface{}{
		(*EditResult_Error)(nil),
		(*EditResult_Id)(nil),
	}
}

func _EditResult_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*EditResult)
	// result
	switch x := m.Result.(type) {
	case *EditResult_Error:
		b.EncodeVarint(1<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Error)
	case *EditResult_Id:
		b.EncodeVarint(2<<3 | proto.WireBytes)
		b.EncodeStringBytes(x.Id)
	case nil:
	default:
		return fmt.Errorf("EditResult.Result has unexpected type %T", x)
	}
	return nil
}

func _EditResult_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*EditResult)
	switch tag {
	case 1: // result.error
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Result = &EditResult_Error{x}
		return true, err
	case 2: // result.id
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.Result = &EditResult_Id{x}
		return true, err
	default:
		return false, nil
	}
}

func _EditResult_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*EditResult)
	// result
	switch x := m.Result.(type) {
	case *EditResult_Error:
		n += proto.SizeVarint(1<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Error)))
		n += len(x.Error)
	case *EditResult_Id:
		n += proto.SizeVarint(2<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Id)))
		n += len(x.Id)
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

type GraphElement struct {
	Graph  string  `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Vertex *Vertex `protobuf:"bytes,2,opt,name=vertex" json:"vertex,omitempty"`
	Edge   *Edge   `protobuf:"bytes,3,opt,name=edge" json:"edge,omitempty"`
	Bundle *Bundle `protobuf:"bytes,4,opt,name=bundle" json:"bundle,omitempty"`
}

func (m *GraphElement) Reset()                    { *m = GraphElement{} }
func (m *GraphElement) String() string            { return proto.CompactTextString(m) }
func (*GraphElement) ProtoMessage()               {}
func (*GraphElement) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *GraphElement) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *GraphElement) GetVertex() *Vertex {
	if m != nil {
		return m.Vertex
	}
	return nil
}

func (m *GraphElement) GetEdge() *Edge {
	if m != nil {
		return m.Edge
	}
	return nil
}

func (m *GraphElement) GetBundle() *Bundle {
	if m != nil {
		return m.Bundle
	}
	return nil
}

type Graph struct {
	Graph    string    `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Edges    []*Edge   `protobuf:"bytes,2,rep,name=edges" json:"edges,omitempty"`
	Vertices []*Vertex `protobuf:"bytes,3,rep,name=vertices" json:"vertices,omitempty"`
}

func (m *Graph) Reset()                    { *m = Graph{} }
func (m *Graph) String() string            { return proto.CompactTextString(m) }
func (*Graph) ProtoMessage()               {}
func (*Graph) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

func (m *Graph) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *Graph) GetEdges() []*Edge {
	if m != nil {
		return m.Edges
	}
	return nil
}

func (m *Graph) GetVertices() []*Vertex {
	if m != nil {
		return m.Vertices
	}
	return nil
}

type ElementID struct {
	Graph string `protobuf:"bytes,1,opt,name=graph" json:"graph,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id" json:"id,omitempty"`
}

func (m *ElementID) Reset()                    { *m = ElementID{} }
func (m *ElementID) String() string            { return proto.CompactTextString(m) }
func (*ElementID) ProtoMessage()               {}
func (*ElementID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *ElementID) GetGraph() string {
	if m != nil {
		return m.Graph
	}
	return ""
}

func (m *ElementID) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Timestamp struct {
	Timestamp string `protobuf:"bytes,1,opt,name=timestamp" json:"timestamp,omitempty"`
}

func (m *Timestamp) Reset()                    { *m = Timestamp{} }
func (m *Timestamp) String() string            { return proto.CompactTextString(m) }
func (*Timestamp) ProtoMessage()               {}
func (*Timestamp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *Timestamp) GetTimestamp() string {
	if m != nil {
		return m.Timestamp
	}
	return ""
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

func init() {
	proto.RegisterType((*GraphQuery)(nil), "aql.GraphQuery")
	proto.RegisterType((*GraphQuerySet)(nil), "aql.GraphQuerySet")
	proto.RegisterType((*GraphStatement)(nil), "aql.GraphStatement")
	proto.RegisterType((*HasStatement)(nil), "aql.HasStatement")
	proto.RegisterType((*HasValueStatement)(nil), "aql.HasValueStatement")
	proto.RegisterType((*SelectStatement)(nil), "aql.SelectStatement")
	proto.RegisterType((*FoldStatement)(nil), "aql.FoldStatement")
	proto.RegisterType((*VertexMatch)(nil), "aql.VertexMatch")
	proto.RegisterType((*GenMatch)(nil), "aql.GenMatch")
	proto.RegisterType((*EdgeGen)(nil), "aql.EdgeGen")
	proto.RegisterType((*Vertex)(nil), "aql.Vertex")
	proto.RegisterType((*Edge)(nil), "aql.Edge")
	proto.RegisterType((*Bundle)(nil), "aql.Bundle")
	proto.RegisterType((*QueryResult)(nil), "aql.QueryResult")
	proto.RegisterType((*ResultRow)(nil), "aql.ResultRow")
	proto.RegisterType((*EditResult)(nil), "aql.EditResult")
	proto.RegisterType((*GraphElement)(nil), "aql.GraphElement")
	proto.RegisterType((*Graph)(nil), "aql.Graph")
	proto.RegisterType((*ElementID)(nil), "aql.ElementID")
	proto.RegisterType((*Timestamp)(nil), "aql.Timestamp")
	proto.RegisterType((*Empty)(nil), "aql.Empty")
	proto.RegisterEnum("aql.Condition", Condition_name, Condition_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Query service

type QueryClient interface {
	Traversal(ctx context.Context, in *GraphQuery, opts ...grpc.CallOption) (Query_TraversalClient, error)
	GetVertex(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Vertex, error)
	GetEdge(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Edge, error)
	GetBundle(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Bundle, error)
	GetGraphs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Query_GetGraphsClient, error)
	GetTimestamp(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Timestamp, error)
}

type queryClient struct {
	cc *grpc.ClientConn
}

func NewQueryClient(cc *grpc.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Traversal(ctx context.Context, in *GraphQuery, opts ...grpc.CallOption) (Query_TraversalClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Query_serviceDesc.Streams[0], c.cc, "/aql.Query/Traversal", opts...)
	if err != nil {
		return nil, err
	}
	x := &queryTraversalClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Query_TraversalClient interface {
	Recv() (*ResultRow, error)
	grpc.ClientStream
}

type queryTraversalClient struct {
	grpc.ClientStream
}

func (x *queryTraversalClient) Recv() (*ResultRow, error) {
	m := new(ResultRow)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *queryClient) GetVertex(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Vertex, error) {
	out := new(Vertex)
	err := grpc.Invoke(ctx, "/aql.Query/GetVertex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetEdge(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Edge, error) {
	out := new(Edge)
	err := grpc.Invoke(ctx, "/aql.Query/GetEdge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetBundle(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Bundle, error) {
	out := new(Bundle)
	err := grpc.Invoke(ctx, "/aql.Query/GetBundle", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetGraphs(ctx context.Context, in *Empty, opts ...grpc.CallOption) (Query_GetGraphsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Query_serviceDesc.Streams[1], c.cc, "/aql.Query/GetGraphs", opts...)
	if err != nil {
		return nil, err
	}
	x := &queryGetGraphsClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Query_GetGraphsClient interface {
	Recv() (*ElementID, error)
	grpc.ClientStream
}

type queryGetGraphsClient struct {
	grpc.ClientStream
}

func (x *queryGetGraphsClient) Recv() (*ElementID, error) {
	m := new(ElementID)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *queryClient) GetTimestamp(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*Timestamp, error) {
	out := new(Timestamp)
	err := grpc.Invoke(ctx, "/aql.Query/GetTimestamp", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Query service

type QueryServer interface {
	Traversal(*GraphQuery, Query_TraversalServer) error
	GetVertex(context.Context, *ElementID) (*Vertex, error)
	GetEdge(context.Context, *ElementID) (*Edge, error)
	GetBundle(context.Context, *ElementID) (*Bundle, error)
	GetGraphs(*Empty, Query_GetGraphsServer) error
	GetTimestamp(context.Context, *ElementID) (*Timestamp, error)
}

func RegisterQueryServer(s *grpc.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Traversal_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GraphQuery)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServer).Traversal(m, &queryTraversalServer{stream})
}

type Query_TraversalServer interface {
	Send(*ResultRow) error
	grpc.ServerStream
}

type queryTraversalServer struct {
	grpc.ServerStream
}

func (x *queryTraversalServer) Send(m *ResultRow) error {
	return x.ServerStream.SendMsg(m)
}

func _Query_GetVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Query/GetVertex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetVertex(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Query/GetEdge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetEdge(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Query/GetBundle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetBundle(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetGraphs_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServer).GetGraphs(m, &queryGetGraphsServer{stream})
}

type Query_GetGraphsServer interface {
	Send(*ElementID) error
	grpc.ServerStream
}

type queryGetGraphsServer struct {
	grpc.ServerStream
}

func (x *queryGetGraphsServer) Send(m *ElementID) error {
	return x.ServerStream.SendMsg(m)
}

func _Query_GetTimestamp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetTimestamp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Query/GetTimestamp",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetTimestamp(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aql.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVertex",
			Handler:    _Query_GetVertex_Handler,
		},
		{
			MethodName: "GetEdge",
			Handler:    _Query_GetEdge_Handler,
		},
		{
			MethodName: "GetBundle",
			Handler:    _Query_GetBundle_Handler,
		},
		{
			MethodName: "GetTimestamp",
			Handler:    _Query_GetTimestamp_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Traversal",
			Handler:       _Query_Traversal_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetGraphs",
			Handler:       _Query_GetGraphs_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "aql.proto",
}

// Client API for Edit service

type EditClient interface {
	AddVertex(ctx context.Context, in *GraphElement, opts ...grpc.CallOption) (*EditResult, error)
	AddEdge(ctx context.Context, in *GraphElement, opts ...grpc.CallOption) (*EditResult, error)
	AddBundle(ctx context.Context, in *GraphElement, opts ...grpc.CallOption) (*EditResult, error)
	StreamElements(ctx context.Context, opts ...grpc.CallOption) (Edit_StreamElementsClient, error)
	AddGraph(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error)
	AddSubGraph(ctx context.Context, in *Graph, opts ...grpc.CallOption) (*EditResult, error)
	DeleteGraph(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error)
	DeleteVertex(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error)
	DeleteEdge(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error)
}

type editClient struct {
	cc *grpc.ClientConn
}

func NewEditClient(cc *grpc.ClientConn) EditClient {
	return &editClient{cc}
}

func (c *editClient) AddVertex(ctx context.Context, in *GraphElement, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/AddVertex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) AddEdge(ctx context.Context, in *GraphElement, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/AddEdge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) AddBundle(ctx context.Context, in *GraphElement, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/AddBundle", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) StreamElements(ctx context.Context, opts ...grpc.CallOption) (Edit_StreamElementsClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Edit_serviceDesc.Streams[0], c.cc, "/aql.Edit/StreamElements", opts...)
	if err != nil {
		return nil, err
	}
	x := &editStreamElementsClient{stream}
	return x, nil
}

type Edit_StreamElementsClient interface {
	Send(*GraphElement) error
	CloseAndRecv() (*EditResult, error)
	grpc.ClientStream
}

type editStreamElementsClient struct {
	grpc.ClientStream
}

func (x *editStreamElementsClient) Send(m *GraphElement) error {
	return x.ClientStream.SendMsg(m)
}

func (x *editStreamElementsClient) CloseAndRecv() (*EditResult, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(EditResult)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *editClient) AddGraph(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/AddGraph", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) AddSubGraph(ctx context.Context, in *Graph, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/AddSubGraph", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) DeleteGraph(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/DeleteGraph", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) DeleteVertex(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/DeleteVertex", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *editClient) DeleteEdge(ctx context.Context, in *ElementID, opts ...grpc.CallOption) (*EditResult, error) {
	out := new(EditResult)
	err := grpc.Invoke(ctx, "/aql.Edit/DeleteEdge", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Edit service

type EditServer interface {
	AddVertex(context.Context, *GraphElement) (*EditResult, error)
	AddEdge(context.Context, *GraphElement) (*EditResult, error)
	AddBundle(context.Context, *GraphElement) (*EditResult, error)
	StreamElements(Edit_StreamElementsServer) error
	AddGraph(context.Context, *ElementID) (*EditResult, error)
	AddSubGraph(context.Context, *Graph) (*EditResult, error)
	DeleteGraph(context.Context, *ElementID) (*EditResult, error)
	DeleteVertex(context.Context, *ElementID) (*EditResult, error)
	DeleteEdge(context.Context, *ElementID) (*EditResult, error)
}

func RegisterEditServer(s *grpc.Server, srv EditServer) {
	s.RegisterService(&_Edit_serviceDesc, srv)
}

func _Edit_AddVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).AddVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/AddVertex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).AddVertex(ctx, req.(*GraphElement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_AddEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).AddEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/AddEdge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).AddEdge(ctx, req.(*GraphElement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_AddBundle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GraphElement)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).AddBundle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/AddBundle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).AddBundle(ctx, req.(*GraphElement))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_StreamElements_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EditServer).StreamElements(&editStreamElementsServer{stream})
}

type Edit_StreamElementsServer interface {
	SendAndClose(*EditResult) error
	Recv() (*GraphElement, error)
	grpc.ServerStream
}

type editStreamElementsServer struct {
	grpc.ServerStream
}

func (x *editStreamElementsServer) SendAndClose(m *EditResult) error {
	return x.ServerStream.SendMsg(m)
}

func (x *editStreamElementsServer) Recv() (*GraphElement, error) {
	m := new(GraphElement)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _Edit_AddGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).AddGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/AddGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).AddGraph(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_AddSubGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Graph)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).AddSubGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/AddSubGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).AddSubGraph(ctx, req.(*Graph))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_DeleteGraph_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).DeleteGraph(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/DeleteGraph",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).DeleteGraph(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_DeleteVertex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).DeleteVertex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/DeleteVertex",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).DeleteVertex(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

func _Edit_DeleteEdge_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ElementID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EditServer).DeleteEdge(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/aql.Edit/DeleteEdge",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EditServer).DeleteEdge(ctx, req.(*ElementID))
	}
	return interceptor(ctx, in, info, handler)
}

var _Edit_serviceDesc = grpc.ServiceDesc{
	ServiceName: "aql.Edit",
	HandlerType: (*EditServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddVertex",
			Handler:    _Edit_AddVertex_Handler,
		},
		{
			MethodName: "AddEdge",
			Handler:    _Edit_AddEdge_Handler,
		},
		{
			MethodName: "AddBundle",
			Handler:    _Edit_AddBundle_Handler,
		},
		{
			MethodName: "AddGraph",
			Handler:    _Edit_AddGraph_Handler,
		},
		{
			MethodName: "AddSubGraph",
			Handler:    _Edit_AddSubGraph_Handler,
		},
		{
			MethodName: "DeleteGraph",
			Handler:    _Edit_DeleteGraph_Handler,
		},
		{
			MethodName: "DeleteVertex",
			Handler:    _Edit_DeleteVertex_Handler,
		},
		{
			MethodName: "DeleteEdge",
			Handler:    _Edit_DeleteEdge_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamElements",
			Handler:       _Edit_StreamElements_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "aql.proto",
}

func init() { proto.RegisterFile("aql.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0x4f, 0x6f, 0xdb, 0xc8,
	0x15, 0x0f, 0x49, 0x51, 0x32, 0x9f, 0x1c, 0x87, 0x9e, 0x4d, 0x1d, 0xae, 0x9a, 0x3f, 0xc6, 0x64,
	0xd3, 0x2a, 0x6a, 0x6a, 0x25, 0xda, 0x74, 0x1b, 0x08, 0x3d, 0x34, 0xde, 0x68, 0x15, 0xa1, 0x59,
	0x07, 0xa1, 0x14, 0x07, 0x0b, 0xf4, 0x42, 0x99, 0x63, 0x99, 0x58, 0x8a, 0x54, 0xc8, 0xa1, 0x53,
	0x37, 0x08, 0x0a, 0x14, 0x3d, 0x15, 0xe8, 0xa9, 0x1f, 0xa4, 0x97, 0x7e, 0x89, 0x9e, 0x7b, 0xec,
	0xb5, 0xe7, 0x7e, 0x86, 0x62, 0xde, 0x0c, 0x29, 0x5a, 0xb2, 0x54, 0xb5, 0x3d, 0x89, 0xef, 0xbd,
	0xdf, 0xfc, 0xe6, 0x37, 0xef, 0xbd, 0x79, 0xa4, 0xc0, 0xf2, 0xde, 0x87, 0x07, 0xb3, 0x24, 0xe6,
	0x31, 0x31, 0xbc, 0xf7, 0x61, 0xe3, 0xf6, 0x24, 0x8e, 0x27, 0x21, 0x6b, 0x7b, 0xb3, 0xa0, 0xed,
	0x45, 0x51, 0xcc, 0x3d, 0x1e, 0xc4, 0x51, 0x2a, 0x21, 0x45, 0x14, 0xad, 0x71, 0x76, 0xda, 0x4e,
	0x79, 0x92, 0x9d, 0x70, 0x19, 0xa5, 0xdf, 0x02, 0xf4, 0x13, 0x6f, 0x76, 0xf6, 0x26, 0x63, 0xc9,
	0x05, 0xb9, 0x09, 0xe6, 0x44, 0x58, 0x8e, 0xb6, 0xaf, 0x35, 0x2d, 0x57, 0x1a, 0xe4, 0x21, 0x98,
	0xef, 0x45, 0xd8, 0xd1, 0xf7, 0x8d, 0x66, 0xbd, 0xf3, 0xd9, 0x81, 0xd8, 0x1f, 0x57, 0x0d, 0xb9,
	0xc7, 0xd9, 0x94, 0x45, 0xdc, 0x95, 0x08, 0xda, 0x85, 0xeb, 0x73, 0xba, 0x21, 0xe3, 0xe4, 0x21,
	0xd4, 0x44, 0x24, 0x60, 0xa9, 0xa3, 0xe1, 0xea, 0x1b, 0xf3, 0xd5, 0x08, 0x72, 0xf3, 0x38, 0xfd,
	0x83, 0x05, 0x3b, 0x97, 0x59, 0x49, 0x0b, 0xb4, 0x63, 0xd4, 0x52, 0xef, 0x34, 0x0e, 0xe4, 0x39,
	0x0e, 0xf2, 0x73, 0x1c, 0xbc, 0x0a, 0x52, 0x7e, 0xec, 0x85, 0x19, 0x7b, 0x79, 0xcd, 0xd5, 0x8e,
	0xc9, 0x0e, 0x68, 0x3d, 0x47, 0x17, 0xba, 0x85, 0xdd, 0x23, 0x0f, 0xc0, 0x38, 0xf3, 0x52, 0xc7,
	0xc4, 0xd5, 0xbb, 0xb8, 0xeb, 0x4b, 0x2f, 0x2d, 0xb8, 0x5f, 0x5e, 0x73, 0x45, 0x9c, 0x3c, 0x83,
	0xad, 0x33, 0x2f, 0x7d, 0xe5, 0x8d, 0x59, 0xe8, 0x54, 0x37, 0xd8, 0xa9, 0x40, 0x93, 0x0e, 0x98,
	0x67, 0x5e, 0x3a, 0xf0, 0x9d, 0xda, 0x06, 0xcb, 0x24, 0x94, 0x3c, 0xc5, 0xdd, 0xd0, 0xe9, 0x6c,
	0xe1, 0xb2, 0xbd, 0x5c, 0x19, 0x3a, 0xcb, 0xf2, 0x0a, 0x24, 0x79, 0x04, 0x7a, 0x10, 0x39, 0xb0,
	0xc1, 0x36, 0x7a, 0x10, 0x91, 0x03, 0x30, 0xe2, 0x8c, 0x3b, 0xf5, 0x0d, 0xe0, 0x02, 0x48, 0x9e,
	0x42, 0x35, 0x88, 0x7a, 0xfe, 0x84, 0x39, 0xdb, 0x1b, 0x2c, 0x51, 0x58, 0xf2, 0x15, 0xd4, 0xe2,
	0x8c, 0xe3, 0xb2, 0xeb, 0x1b, 0x2c, 0xcb, 0xc1, 0xe4, 0x31, 0x54, 0xc6, 0x31, 0x3f, 0x73, 0x76,
	0x36, 0x58, 0x84, 0x48, 0x51, 0x21, 0xf1, 0x8b, 0x5b, 0xdd, 0xd8, 0xa4, 0x42, 0x39, 0x9a, 0x74,
	0xc1, 0x8a, 0x33, 0x7e, 0x98, 0x45, 0x7e, 0xc8, 0x1c, 0x7b, 0x83, 0xa5, 0x73, 0x38, 0xb1, 0x41,
	0xf7, 0x52, 0xe7, 0xa6, 0xea, 0x27, 0xdd, 0x4b, 0xc9, 0x01, 0x54, 0x53, 0x16, 0xb2, 0x13, 0xee,
	0xfc, 0x00, 0xa9, 0x6e, 0x62, 0xe5, 0x86, 0xe8, 0x2a, 0xd7, 0x4d, 0xa1, 0x04, 0xfe, 0x5c, 0xf0,
	0xa6, 0xce, 0xde, 0x7a, 0xbc, 0x44, 0x91, 0x3d, 0x30, 0xc3, 0x60, 0x1a, 0x70, 0xe7, 0xf3, 0x7d,
	0xad, 0x69, 0x88, 0x9e, 0x41, 0x53, 0xf8, 0x4f, 0xe2, 0x2c, 0xe2, 0x4e, 0x43, 0x89, 0x91, 0x26,
	0xd9, 0x07, 0x98, 0x24, 0x71, 0x36, 0xfb, 0x1a, 0x83, 0x77, 0x55, 0xb0, 0xe4, 0x23, 0x2d, 0x30,
	0xa7, 0x1e, 0x3f, 0x39, 0x73, 0x9a, 0x28, 0x80, 0x2c, 0x5c, 0xbd, 0x21, 0x13, 0xdb, 0x4b, 0x08,
	0x71, 0xa0, 0x1a, 0x4c, 0x67, 0x71, 0xc2, 0x9d, 0x8e, 0x62, 0x52, 0x36, 0x21, 0x60, 0x4c, 0xbd,
	0x99, 0xf3, 0xa5, 0x72, 0x0b, 0x83, 0x34, 0xa1, 0x72, 0x1a, 0x87, 0xbe, 0xf3, 0xb4, 0x44, 0xfc,
	0x4d, 0x1c, 0xfa, 0xe5, 0x73, 0x21, 0x82, 0x3c, 0x05, 0x38, 0x67, 0x09, 0x67, 0xbf, 0x11, 0x61,
	0xe7, 0x67, 0x6b, 0xf0, 0x25, 0x9c, 0x50, 0x73, 0x1a, 0x84, 0x9c, 0x25, 0xce, 0x57, 0xb9, 0x1a,
	0x69, 0x93, 0x2f, 0x60, 0x5b, 0x3e, 0x1d, 0xcb, 0xdc, 0xfe, 0x5c, 0xc5, 0x2f, 0x79, 0xc9, 0x23,
	0xb0, 0x15, 0x5b, 0x12, 0x4f, 0x15, 0xf2, 0x99, 0x42, 0x2e, 0x45, 0x0e, 0xeb, 0x60, 0xa5, 0xb9,
	0x10, 0xfa, 0x0c, 0xb6, 0xcb, 0x73, 0x82, 0xd8, 0x60, 0x7c, 0xcf, 0x2e, 0xd4, 0x44, 0x14, 0x8f,
	0x64, 0x0f, 0xaa, 0x1f, 0x02, 0x7e, 0x16, 0x44, 0x38, 0x10, 0x2d, 0x57, 0x59, 0x34, 0x80, 0xdd,
	0xa5, 0x7b, 0x4c, 0x08, 0x54, 0xbe, 0x67, 0x17, 0x4f, 0xd4, 0x7a, 0x7c, 0x56, 0xbe, 0x8e, 0x9c,
	0x56, 0xe8, 0xeb, 0x90, 0x47, 0x60, 0x9d, 0xc4, 0x91, 0x1f, 0x88, 0xd1, 0xed, 0x18, 0xfb, 0x5a,
	0x73, 0xa7, 0xb3, 0x83, 0x69, 0xfa, 0x3a, 0xf7, 0xba, 0x73, 0x00, 0x7d, 0x08, 0x37, 0x16, 0x1a,
	0x49, 0xa8, 0x0a, 0xc5, 0x5c, 0x92, 0x83, 0xd6, 0x72, 0x95, 0x45, 0x87, 0x70, 0xfd, 0x52, 0xa6,
	0x05, 0x30, 0x8d, 0xb3, 0xe4, 0x84, 0x29, 0x4d, 0xca, 0x22, 0x2d, 0xa8, 0x04, 0x51, 0xc0, 0x51,
	0x95, 0x98, 0x4b, 0x8b, 0x17, 0x05, 0x0f, 0xe6, 0x22, 0x86, 0x7e, 0x07, 0xf5, 0x63, 0xcc, 0xe2,
	0xb7, 0xd8, 0x3c, 0x37, 0xc1, 0x3c, 0x0d, 0x58, 0xe8, 0xe7, 0xef, 0x0d, 0x34, 0x84, 0x17, 0x5b,
	0x5b, 0xa5, 0x49, 0x1a, 0xe4, 0x2e, 0xe8, 0xf1, 0x6c, 0xc5, 0x09, 0xf5, 0x78, 0x46, 0x7f, 0x0d,
	0x5b, 0x7d, 0x16, 0xad, 0xe3, 0xfd, 0x51, 0xde, 0xd6, 0xf2, 0x7d, 0x64, 0x23, 0x49, 0x49, 0x4e,
	0xde, 0xd2, 0x04, 0x2a, 0xbe, 0xc7, 0x3d, 0xdc, 0xcb, 0x72, 0xf1, 0x99, 0xfe, 0x45, 0x83, 0x9a,
	0x98, 0x0d, 0x7d, 0x16, 0x89, 0xca, 0x4e, 0x82, 0x9c, 0x5b, 0x3c, 0x8a, 0xfd, 0x30, 0x6b, 0xaa,
	0x32, 0xd2, 0x20, 0x0f, 0xc0, 0xcc, 0xa2, 0xdf, 0x06, 0x52, 0x74, 0xbd, 0x73, 0x5d, 0x5e, 0x23,
	0xa5, 0x51, 0xdc, 0x20, 0x8c, 0x0a, 0x58, 0xe2, 0x45, 0x13, 0xe6, 0x54, 0x56, 0xc0, 0x30, 0x2a,
	0x60, 0x52, 0xbd, 0xb9, 0x02, 0x86, 0xd1, 0xc3, 0x1a, 0x98, 0xe3, 0x2c, 0x08, 0x7d, 0xfa, 0x09,
	0xaa, 0xf2, 0x6c, 0x1b, 0xeb, 0xfd, 0x49, 0xe9, 0xdc, 0xf5, 0xce, 0xad, 0xa5, 0x42, 0x0e, 0xf1,
	0x03, 0x40, 0x26, 0x84, 0xdc, 0x05, 0x63, 0xc2, 0x22, 0xa7, 0x82, 0xa9, 0xdc, 0x46, 0x31, 0x2a,
	0x3f, 0xae, 0x08, 0xd0, 0xdf, 0x41, 0x05, 0x67, 0xe9, 0xa6, 0x9b, 0x13, 0xa8, 0x9c, 0x26, 0xf1,
	0x34, 0x4f, 0xba, 0x78, 0x26, 0x3b, 0xa0, 0xf3, 0x18, 0xd3, 0x62, 0xb9, 0x3a, 0x8f, 0x0b, 0x81,
	0xe6, 0x06, 0x02, 0xe9, 0xdf, 0x34, 0xa8, 0x16, 0x33, 0xf9, 0x7f, 0xd7, 0xd0, 0x86, 0xea, 0x58,
	0xbe, 0x08, 0xe4, 0x51, 0x6f, 0xe1, 0x51, 0x25, 0xb1, 0xfa, 0xe9, 0x45, 0x3c, 0xb9, 0x70, 0x15,
	0xac, 0xe1, 0x42, 0xbd, 0xe4, 0xbe, 0x62, 0x0c, 0xfc, 0x74, 0xde, 0xde, 0x6b, 0x8f, 0x21, 0x51,
	0x5d, 0xfd, 0x99, 0x46, 0xff, 0xaa, 0x41, 0x5d, 0x7e, 0xf5, 0xb0, 0x34, 0x0b, 0x39, 0x79, 0x00,
	0x55, 0x39, 0x8c, 0xd4, 0x47, 0x4e, 0xbd, 0xd4, 0xca, 0xf8, 0x66, 0x90, 0x85, 0xbf, 0x07, 0x15,
	0x26, 0xde, 0x7e, 0x72, 0x23, 0xab, 0x28, 0x92, 0x18, 0xb2, 0x22, 0x20, 0x78, 0xd4, 0xe1, 0x8c,
	0x12, 0x8f, 0x94, 0x2f, 0x78, 0x64, 0x90, 0x3c, 0x52, 0x79, 0xaf, 0xac, 0xbb, 0xe1, 0x82, 0x54,
	0xa0, 0x0e, 0xb7, 0xa0, 0x9a, 0xa0, 0x4c, 0xfa, 0x0e, 0x2c, 0x29, 0xd8, 0x8d, 0x3f, 0x88, 0xdb,
	0x27, 0x8f, 0x2d, 0x25, 0xcb, 0xdb, 0x57, 0x3a, 0x54, 0x7e, 0xcf, 0x29, 0x18, 0x49, 0xfc, 0xe1,
	0xd2, 0x1d, 0x2d, 0xa3, 0x44, 0x90, 0xfe, 0x12, 0xa0, 0xe7, 0x07, 0x5c, 0x65, 0x63, 0x0f, 0x4c,
	0x96, 0x24, 0x71, 0x22, 0x93, 0x2c, 0xae, 0x02, 0x9a, 0xe2, 0x55, 0x1c, 0xf8, 0xc5, 0xa7, 0x9d,
	0x1e, 0xf8, 0x25, 0x69, 0x7f, 0xd2, 0x60, 0x1b, 0xdf, 0x68, 0xbd, 0x50, 0x4e, 0xb7, 0xab, 0x3f,
	0x61, 0xef, 0x17, 0x89, 0xd6, 0x97, 0x12, 0x5d, 0xa4, 0xf9, 0x8e, 0x4a, 0xb3, 0xb1, 0x90, 0x66,
	0x95, 0xe4, 0xfb, 0xa5, 0x0e, 0x5a, 0x4c, 0x72, 0x9e, 0x62, 0x3a, 0x01, 0x13, 0xe5, 0xac, 0xd0,
	0x71, 0x0f, 0x4c, 0xc1, 0x95, 0xaa, 0xb4, 0x94, 0xf6, 0x90, 0x7e, 0xf2, 0x63, 0xd8, 0x12, 0x6a,
	0x82, 0x13, 0x96, 0x3a, 0x06, 0x62, 0x2e, 0x49, 0x2d, 0x82, 0xf4, 0x09, 0x58, 0xea, 0xc8, 0x83,
	0x17, 0x2b, 0x36, 0xdb, 0x99, 0xe7, 0x4d, 0x64, 0x8d, 0x3e, 0x04, 0x6b, 0x14, 0x4c, 0x59, 0xca,
	0xbd, 0xe9, 0x8c, 0xdc, 0x06, 0x8b, 0xe7, 0x86, 0x5a, 0x36, 0x77, 0xd0, 0x1a, 0x98, 0xbd, 0xe9,
	0x8c, 0x5f, 0xb4, 0xfe, 0xa8, 0x81, 0x55, 0xcc, 0x67, 0x52, 0x87, 0xda, 0xdb, 0xa3, 0x5f, 0x1d,
	0xbd, 0x7e, 0x77, 0x64, 0x5f, 0x23, 0x55, 0xd0, 0x7b, 0x6f, 0x6c, 0x8d, 0xd4, 0xc0, 0x38, 0xea,
	0xbd, 0xb1, 0x75, 0xe1, 0xe8, 0x8f, 0x6c, 0x43, 0x38, 0xfa, 0xa3, 0x9e, 0x5d, 0x11, 0x8e, 0x57,
	0x23, 0xdb, 0x14, 0x8e, 0x57, 0xa3, 0x9e, 0x5d, 0x15, 0xeb, 0x0f, 0x7b, 0xa3, 0x77, 0xbd, 0xde,
	0x91, 0x5d, 0x23, 0x00, 0xd5, 0xc1, 0xd1, 0x70, 0xf0, 0xa2, 0x67, 0x6f, 0x89, 0xc0, 0xeb, 0xb7,
	0x23, 0x34, 0x2c, 0x11, 0x78, 0x37, 0x18, 0xbd, 0x1c, 0x1c, 0xd9, 0x20, 0x02, 0xe2, 0xf9, 0xf5,
	0xdb, 0x91, 0x5d, 0xef, 0xfc, 0xc3, 0x00, 0x53, 0xfe, 0x51, 0x71, 0xc1, 0x1a, 0x25, 0xde, 0x39,
	0x4b, 0x52, 0x2f, 0x24, 0x8b, 0x7f, 0x29, 0x1a, 0xf2, 0xb5, 0x52, 0xb4, 0x2c, 0xa5, 0xbf, 0xff,
	0xfb, 0x3f, 0xff, 0xac, 0xdf, 0xa6, 0xb7, 0xda, 0xe7, 0x4f, 0xda, 0x98, 0x9b, 0xf6, 0x47, 0xfc,
	0xf9, 0xd4, 0xc6, 0xbf, 0x2d, 0x5d, 0xad, 0xf5, 0x58, 0x23, 0xaf, 0xc1, 0xea, 0x33, 0xae, 0x66,
	0xad, 0xa4, 0x28, 0x32, 0xdc, 0x28, 0x57, 0x81, 0x3e, 0x40, 0xbe, 0x7b, 0xe4, 0xce, 0x32, 0x9f,
	0x6c, 0xa5, 0xf6, 0xc7, 0xc0, 0xff, 0x44, 0x06, 0x50, 0xeb, 0x33, 0xf9, 0xd5, 0xbb, 0x48, 0x37,
	0x2f, 0x3c, 0xbd, 0x8f, 0x64, 0x77, 0xc8, 0x0f, 0x97, 0xc9, 0x44, 0x4b, 0x48, 0x2a, 0xa9, 0x4d,
	0x8d, 0xc1, 0xab, 0xb5, 0xc9, 0xe0, 0x3a, 0x6d, 0xb2, 0x45, 0x25, 0xe1, 0x2f, 0x90, 0x10, 0x73,
	0x96, 0x12, 0x90, 0x84, 0xa2, 0xe0, 0x8d, 0x05, 0x72, 0xba, 0x8b, 0x7c, 0x75, 0x62, 0x15, 0x7c,
	0x8f, 0x35, 0x32, 0x84, 0xed, 0x3e, 0xe3, 0xf3, 0x66, 0x5a, 0x54, 0x24, 0xed, 0x22, 0xbe, 0xee,
	0x8c, 0x45, 0xcf, 0x75, 0xfe, 0x65, 0x8a, 0x57, 0x4d, 0xc0, 0xc9, 0x77, 0x60, 0x3d, 0xf7, 0x7d,
	0x55, 0x88, 0xdd, 0x79, 0x71, 0x15, 0x7f, 0xe3, 0x86, 0x4a, 0x5e, 0x3e, 0x38, 0x68, 0x13, 0xe9,
	0x29, 0x75, 0x56, 0xd5, 0xa3, 0x9b, 0x5f, 0xf1, 0x21, 0xd4, 0x9e, 0xfb, 0x3e, 0x96, 0x64, 0x13,
	0xe2, 0x2f, 0x90, 0xf8, 0x2e, 0xdd, 0xbb, 0xba, 0x36, 0x5d, 0x39, 0x18, 0xa4, 0x5e, 0x55, 0x9c,
	0xff, 0x53, 0xaf, 0xac, 0x51, 0x37, 0x9f, 0xd8, 0x03, 0xd8, 0x19, 0xf2, 0x84, 0x79, 0x53, 0xc5,
	0x95, 0x6e, 0xc4, 0xaf, 0x6a, 0x46, 0xe7, 0x35, 0x6b, 0x6a, 0xe4, 0x1b, 0xd8, 0x7a, 0xee, 0xfb,
	0x72, 0x38, 0x2d, 0xd6, 0x6b, 0x89, 0xe1, 0x73, 0x64, 0xf8, 0x8c, 0xee, 0x2e, 0x29, 0x24, 0x6f,
	0xa0, 0xfe, 0xdc, 0xf7, 0x87, 0xd9, 0x58, 0x52, 0xc1, 0x5c, 0xcf, 0x32, 0x8d, 0x6a, 0x46, 0xda,
	0x58, 0x3e, 0x68, 0x9a, 0x8d, 0xf1, 0xa9, 0xab, 0xb5, 0xc8, 0x00, 0xea, 0x2f, 0x58, 0xc8, 0x38,
	0xfb, 0xef, 0xd4, 0xb5, 0xae, 0x50, 0x77, 0x0c, 0xdb, 0x92, 0x6a, 0xc5, 0x3d, 0x5e, 0x25, 0xb1,
	0xf5, 0x1f, 0xee, 0xb2, 0x0b, 0x20, 0x79, 0xaf, 0xbc, 0xce, 0x4b, 0xac, 0xaa, 0xe1, 0x5b, 0xeb,
	0x2e, 0xf5, 0xb8, 0x8a, 0x2f, 0xde, 0x2f, 0xff, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xba, 0x9e, 0xac,
	0xca, 0xd0, 0x11, 0x00, 0x00,
}
